[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    	Access-Control-Allow-Origin = "https://verkkosivuista.foxnet.fi"
		X-Frame-Options = "SAMEORIGIN"
		X-XXS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"
