# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 06:15 daily. https://crontab.guru/#15_6_*_*_*
    - cron: '15 6 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
